name: SonarCloud
# Trigger analysis when creating a pull request
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, test, and analyze
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Ensures full history for more accurate Sonar analysis

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      # Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Run PHPUnit (coverage is defined in phpunit.xml.dist)
      - name: Run tests with coverage
        run: composer test

      # Set up JDK (required by SonarCloud scanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sekhubede
            -Dsonar.projectKey=sekhubede_gondwana-api-assignment
            -Dsonar.php.coverage.reportPaths=coverage.xml